export enum ReviewSessionStatus {
  PENDING = 'PENDING',
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  EXPIRED = 'EXPIRED',
}

export enum ReviewStatus {
  PENDING_MODERATION = 'PENDING_MODERATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED',
}

export enum ReviewMediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  VOICE = 'VOICE',
}

export enum ReviewSource {
  INVOICE = 'INVOICE',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  DIRECT = 'DIRECT',
}

export enum ReviewEventType {
  QR_SCANNED = 'QR_SCANNED',
  EMAIL_CLICKED = 'EMAIL_CLICKED',
  WHATSAPP_CLICKED = 'WHATSAPP_CLICKED',
  PAGE_OPENED = 'PAGE_OPENED',
  PRODUCT_SELECTED = 'PRODUCT_SELECTED',
  RATING_SELECTED = 'RATING_SELECTED',
  REVIEW_STARTED = 'REVIEW_STARTED',
  TEXT_STARTED = 'TEXT_STARTED',
  VOICE_STARTED = 'VOICE_STARTED',
  PHOTO_UPLOADED = 'PHOTO_UPLOADED',
  VIDEO_UPLOADED = 'VIDEO_UPLOADED',
  AI_GENERATION_STARTED = 'AI_GENERATION_STARTED',
  AI_GENERATION_COMPLETED = 'AI_GENERATION_COMPLETED',
  REVIEW_EDITED = 'REVIEW_EDITED',
  REVIEW_SUBMITTED = 'REVIEW_SUBMITTED',
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  REVIEW_PUBLISHED = 'REVIEW_PUBLISHED',
  GOOGLE_CLICKED = 'GOOGLE_CLICKED',
}
